version: '3.8' # Specifies the Docker Compose file version.

x-global-environment: &global-environment
  SERVICE_DISCOVERY_SERVER_URL: http://service-discovery:8761/eureka/
  SERVICE_DISCOVERY_HOST: service-discovery
  ZIPKIN_SERVER_URL: http://zipkin:9411/api/v2/spans
  CONFIG_SERVER_URL: http://config-server:8888

services: # Defines the services that make up your application run as container.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  service-discovery: # Service Discovery container configuration.
    container_name: service-discovery
    image: eshop/service-discovery:latest
    build: # Build the image for this service.
      context: ./service-discovery # Context directory for the build.
    ports:
      - "8761:8761"  # Map port 8761 on the host to port 8761 in the container.
    depends_on:
      - zipkin
    environment:
      <<: *global-environment

  config-server:
    container_name: config-server
    image: eshop/config-server:latest
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on: # This service depends on following services
      - zipkin
      - service-discovery
    environment:
      <<: *global-environment

  apigateway:
    container_name: apigateway
    image: eshop/apigateway:latest
    build:
      context: ./apigateway
    ports:
      - "9000:9000"
    depends_on:
      - zipkin
      - service-discovery
      - config-server
    environment:
      <<: *global-environment

  product-api:
    container_name: product-api
    image: eshop/product-api:latest
    build:
      context: ./product-api
    ports:
      - "9002:9002"
    depends_on:
      - zipkin
      - service-discovery
      - config-server
      - apigateway
    environment:
      <<: *global-environment
